language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
before_install: "gem update --system"

env:
  - CI=true
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9
  - rbx-3
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
dist: trusty
